### PR TITLE
Bump github.com/bytedance/sonic to v1.14.0 for Go 1.25 compatibility

### LINKED ISSUE #6335: [BUG] fails to build with Go 1.25
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Build with Go 1.25 (rc2) fails.

### Expected Behavior

Build with Go 1.25 should succeed.

### Steps To Reproduce

1) Install Go 1.25 (rc2): https://go.dev/dl/#go1.25rc2
2) Update Makefile to use go 1.25 if needed in https://github.com/projectdiscovery/nuclei/blob/9133e0d2d0ec60637a421ab4c2faad100067a339/Makefile#L2
  to eg:
  ```Makefile
  GOCMD := go1.25rc2
  ```
3) run `make build`

### Relevant log output

```shell
$ make build
rm -f './bin/nuclei' 2>/dev/null
CGO_ENABLED=0 go1.25rc2 build -trimpath -v -pgo=auto -ldflags '-s -w'  \
                 -o './bin/nuclei' cmd/nuclei/main.go
github.com/bytedance/sonic/internal/rt
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [go-build] Error 1
```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

### Anything else?

👋  During the testing of Go 1.25rc2 in
* https://github.com/Homebrew/homebrew-core/pull/226636

it was noted that the build of nuclei [fails](https://github.com/Homebrew/homebrew-core/actions/runs/16153392582/job/45592401053?pr=226636#step:3:20308) with:
```
  # github.com/bytedance/sonic/internal/rt
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
```

The upstream module `github.com/bytedance/sonic` already has a fix 
* https://github.com/bytedance/sonic/pull/808

merged and available in the [v1.14.0-rc1](https://github.com/bytedance/sonic/releases/tag/v1.14.0-rc1) prerelease. Initial testing shows that updating that module fixes the build.

Please
* `go get -u github.com/bytedance/sonic@v1.14.0-rc1`
* run the CI tests to make sure nothing is broken
* test with Go 1.25rc2 and fix any other changes needed and/or report bugs upstream
* wait until 1.14.0 or later [release](https://github.com/bytedance/sonic/releases) is available
* update the `github.com/bytedance/sonic` module (eg via `go get -u github.com/bytedance/sonic@latest`)
* create a release

Please note that Go 1.25 release is scheduled for August. It would be ideal if you make a release with Go 1.25 support before that or at least immediately after the release.

Related:
* https://github.com/projectdiscovery/nuclei/issues/6331

### PR DESCRIPTION
**Pull request by stefanb**
## Proposed changes

Fixes #6335
by using https://github.com/bytedance/sonic/releases/tag/v1.14.0

Log:
```
$ go get github.com/bytedance/sonic@v1.14.0 && go mod tidy
go: upgraded github.com/bytedance/sonic v1.13.3 => v1.14.0
go: upgraded github.com/bytedance/sonic/loader v0.2.4 => v0.3.0
```

Related:
* upstream: https://github.com/bytedance/sonic/pull/808
* downstream: https://github.com/Homebrew/homebrew-core/pull/226636

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: pkg/utils/json/doc.go [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // Package json provides fast JSON encoding and decoding functionality.
 //
 // On supported platforms; Linux, Darwin, or Windows on amd64, or on arm64 with
-// Go >= 1.20 and <= 1.24, the package uses the high-performance [sonic] library.
+// Go >= 1.20 and <= 1.25, the package uses the high-performance [sonic] library.
```
Comment (stefanb) [inline pkg/utils/json/doc.go:4]: Thanks, @dwisiswant0 !

**Comment by Elsfa7-110** [comment]
go install -v github.com/bytedance/sonic@v1.14.0 && go mod tidy
package github.com/bytedance/sonic is not a main package

go get not working also
