### ISSUE TITLE
[BUG] fails to build with Go 1.25

### ISSUE THREAD

**Issue by stefanb** [projectdiscovery/nuclei#6335]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Build with Go 1.25 (rc2) fails.

### Expected Behavior

Build with Go 1.25 should succeed.

### Steps To Reproduce

1) Install Go 1.25 (rc2): https://go.dev/dl/#go1.25rc2
2) Update Makefile to use go 1.25 if needed in https://github.com/projectdiscovery/nuclei/blob/9133e0d2d0ec60637a421ab4c2faad100067a339/Makefile#L2
  to eg:
  ```Makefile
  GOCMD := go1.25rc2
  ```
3) run `make build`

### Relevant log output

```shell
$ make build
rm -f './bin/nuclei' 2>/dev/null
CGO_ENABLED=0 go1.25rc2 build -trimpath -v -pgo=auto -ldflags '-s -w'  \
                 -o './bin/nuclei' cmd/nuclei/main.go
github.com/bytedance/sonic/internal/rt
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [go-build] Error 1
```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

### Anything else?

👋  During the testing of Go 1.25rc2 in
* https://github.com/Homebrew/homebrew-core/pull/226636

it was noted that the build of nuclei [fails](https://github.com/Homebrew/homebrew-core/actions/runs/16153392582/job/45592401053?pr=226636#step:3:20308) with:
```
  # github.com/bytedance/sonic/internal/rt
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
```

The upstream module `github.com/bytedance/sonic` already has a fix 
* https://github.com/bytedance/sonic/pull/808

merged and available in the [v1.14.0-rc1](https://github.com/bytedance/sonic/releases/tag/v1.14.0-rc1) prerelease. Initial testing shows that updating that module fixes the build.

Please
* `go get -u github.com/bytedance/sonic@v1.14.0-rc1`
* run the CI tests to make sure nothing is broken
* test with Go 1.25rc2 and fix any other changes needed and/or report bugs upstream
* wait until 1.14.0 or later [release](https://github.com/bytedance/sonic/releases) is available
* update the `github.com/bytedance/sonic` module (eg via `go get -u github.com/bytedance/sonic@latest`)
* create a release

Please note that Go 1.25 release is scheduled for August. It would be ideal if you make a release with Go 1.25 support before that or at least immediately after the release.

Related:
* https://github.com/projectdiscovery/nuclei/issues/6331

**Comment by dogancanbakir** [comment]
@stefanb Thanks for the update! We'll look into it!

**Comment by stefanb** [comment]
@dogancanbakir, upstream made a release, so I prepared the fix in:
* https://github.com/projectdiscovery/nuclei/pull/6348

**Comment by dogancanbakir** [comment]
@stefanb Thanks for the PR!
